# Generated by Django 4.0.3 on 2022-03-08 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_position_remove_person_is_superuser_person_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='example.position'),
        ),
    ]
