# Generated by Django 4.0.3 on 2022-03-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_alter_person_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='example.position'),
            preserve_default=False,
        ),
    ]
