# Generated by Django 4.0.3 on 2022-03-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_alter_person_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='person',
            name='userid',
        ),
    ]
